# Generated by Django 5.2.5 on 2025-10-19 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_genre_options_alter_person_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmwork',
            options={'verbose_name': 'film work', 'verbose_name_plural': 'film works'},
        ),
        migrations.AlterModelOptions(
            name='genrefilmwork',
            options={'verbose_name': 'genre of film work', 'verbose_name_plural': 'genres of film works'},
        ),
        migrations.AlterModelOptions(
            name='personfilmwork',
            options={'verbose_name': 'film work participant', 'verbose_name_plural': 'film work participants'},
        ),
    ]
